#!/usr/bin/env python
# -*- coding: utf-8 -*- 

import argparse
import sys
import os
from random import randint

estados_validos = ['completo', 'parcial', 'aleatorio']
ranges_validos = ['pequeno', 'grande']
tamanhos_validos = ['pequeno', 'grande']

def main(args):
    estado = args.estado
    data_range = args.range
    tamanho = args.tamanho

    f = open("data/" + estado + "_" + data_range + "_" + tamanho + ".txt", "w+")

    range_value = 50 if data_range == "pequeno" else 100
    tamanho_value = 100000 if tamanho == "pequeno" else 2000000

    if estado == "completo":
        for i in range(0, (tamanho_value*range_value), range_value):
            f.write(str(i) + "\n")
    elif estado == "parcial":
        for i in range((tamanho_value/3)*range_value, -1, -range_value):
            f.write(str(i) + "\n")
        for i in range(range_value*2*(tamanho_value/3), range_value*tamanho_value, range_value):
            f.write(str(i) + "\n")
        for i in range(range_value*(tamanho_value/3) + 1, range_value*2*(tamanho_value/3), range_value):
            f.write(str(i) + "\n")
    else:
        for i in range(tamanho_value):
            f.write(str(randint(0, tamanho_value) + range_value) + "\n")
    f.close()

def verify_get_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('estado', help='estado dos dados de entrada')
    parser.add_argument('range', help='tamanho do range')
    parser.add_argument('tamanho', help='tamanho da entrada')
    if len(sys.argv[1:]) < 3: 
        print "You must inform the attributes to generate the input file"
        sys.exit()
    
    estado = sys.argv[1]
    data_range = sys.argv[2]
    tamanho = sys.argv[3]
    if not estado or not data_range or not tamanho:
        print "You must insert three attributes: estado, data_range and tamanho"
    if (not estado in estados_validos) or (not data_range in ranges_validos) or (not tamanho in tamanhos_validos):
        print "Estado must be 'completo' or 'parcial' or 'aleatorio'\n" \
        "Range must be 'pequeno' or 'grande'\n"\
        "Tamanho must be 'pequeno' or 'grande'"
    return parser.parse_args()

if __name__ == "__main__":
    args = verify_get_args()
    main(args)